#!/bin/bash
#                   \    |    _ _|    \     __|  __|   __|
#                  _ \   |      |    _ \  \__ \  _|  \__ \
#                _/  _\ ____| ___| _/  _\ ____/ ___| ____/
################################################################################
# ▸ ~/.anarchy/aliases
################################################################################
# 1 DANK U WEL
################################################################################
#
# "arco" (ˈɑːkəʊ') british english : adverb
# A musical direction for instruments of the violin family, indicating that the
# bow should be used (as opposed to plucking strings).
#
alias eeuwig_dankbaar="echo 'Mr. Dubois'"
alias en_blijf_rollen="echo 'Arco Team!'"
################################################################################
# 3 COMMANDS
################################################################################
alias af='lynx -dump -width=500 http://localhost:80/whm-server-status'
alias att='archlinux-tweak-tool'
alias bup="sh -c $ANARCHY/backup"
alias bupskel='cp -Rf /etc/skel ~/.skel-backup-$(date +%Y.%m.%d-%H.%M.%S)'
alias calc='galculator'
alias chars='gucharmap'
alias chkcpu='cpuid -i | grep uarch | head -n 1'
alias chkefi="ls '/sys/firmware/efi/efivars'"
alias chk='readFiles'
alias chktodo="readFiles $ANARCHY/checklist.txt"
alias chkvul="grep . '/sys/devices/system/cpu/vulnerabilities/*'"
alias colors='export LS_COLORS="$(cat "$HOME/.dircolors")"'
alias cp='cp -rp'
alias dbn='deadbeef --next &'
alias dbp='deadbeef --prev &'
alias dbpp='deadbeef --play-pause &'
alias dbr='deadbeef --random &'
alias dbs='get_dead'
alias df='df -h'
alias downn='shutdown now'
alias du='du -sh'
alias ev='evince'
alias free='free -wh'
alias fuckoff='faillock --user "$USER" --reset'
alias fuck="sh -c $ANARCHY/secretary"
alias ged='gedit'
alias gednew='gedit --new-window'
alias gpgchk='gpg --keyserver-options auto-key-retrieve --verify'
alias gpgget='gpg --keyserver-options auto-key-retrieve --receive-keys'
alias gpull='git pull'
alias grep='grep --color=always'
alias grh='git reset --hard'
alias grmcache="rm -r ~/.cache/git"
alias hl='highlight --out-format=ansi'
alias hw='hwinfo --short'
alias ipp='curl ifconfig.me; echo'
alias jctler="journalctl -x -o short | grep -i 'error'"
alias jctlex="journalctl -x -o short | grep -i 'exit code 1'"
alias jctlfl="journalctl -x -o short | grep -i 'failed'"
alias jctl='journalctl -p 3 -xb'
alias k9='killall -qv -9'
alias lcalamares='readFiles /var/log/Calamares.log'
alias less='less --use-color'
alias ll='ls -la'
alias lpacman='readFiles /var/log/pacman.log'
alias ls='ls -Nh --color=always'
alias lsusers='cut -d: -f1 /etc/passwd | sort'
alias lv='ls -vCa'
alias lxorg="readFiles $HOME/.local/share/xorg/Xorg.0.log"
alias mnt="mounter &>'/dev/null'"
alias mvp='mkdir -vp'
alias nemo='nemo .'
alias nmactv='nmcli -p c show --active'
alias nmdevs='nmcli -p d'
alias nmperms='nmcli -p g perm'
alias nmprofs='nmcli -p c'
alias nmradio='nmcli -p r'
alias nmwifi='nmcli -p d wifi list'
alias nn='rnano -w'
alias pacman='pacman --color auto'
alias pj='ps -ja'
alias plk='pulseaudio --kill'
alias pls='pulseaudio --start'
alias psg='psGrep'
alias puppetsync='puppet agent --test --verbose --trace'
alias py='python'
alias qv="qview &>'/dev/null'"
alias reload='reload'
alias reqs='deps -r'
alias rip="expac --timefmt='%Y-%m-%d %T' '%l\t%n %v' | sort | tail -200 | nl"
alias rmr='rm -r'
alias scp='scp -rp'
alias shot='gnome-screenshot -a'
alias sserver="pactl info | grep 'Server Name'"
alias steampath="unlink $HOME/.steampath"
alias steampid="unlink $HOME/.steampid"
alias steam='steam_mod'
alias stopx='pkill -15 -t tty"$XDG_VTNR" Xorg'
alias term='terminator'
alias tree='tree -a'
alias umnt="unmounter &>'/dev/null'"
alias updtodo="gedit --new-window $ANARCHY/checklist.txt"
alias up='uptime -p'
alias userlist="cut -d: -f1 /etc/passwd | sort"
alias viv='vivaldi-stable'
alias wget='wget -c'
alias whichvga='/usr/local/bin/arcolinux-which-vga'
alias xd='ls /usr/share/xsessions'
alias xdw='ls /usr/share/wayland-sessions'
alias xr='xreader'
alias yskip='yay -S --mflags --skipinteg'
alias yss='yay -Ss'
alias lbup="readFiles $ANARCHY/bup.log" 
################################################################################
# 4 SUDO MODS
################################################################################
alias fixloadkeys='sudo sed -i '\''$d'\'' "/etc/vconsole.conf"'
alias fuckup='sudo $(history -p \!\!)'
alias gkscalamares='gksudo calamares'
alias sblkid='sudo blkid'
alias scat='sudo cat'
alias schattr='sudo chattr'
alias schgrp='sudo chgrp'
alias schmod='sudo chmod'
alias schown='sudo chown'
alias sctl='sudo systemctl'
alias scuttle='sudo scuttle'
alias sdif='sudo diff'
alias seject='sudo eject'
alias setfonts='sudo fc-cache -fv'
alias setgrubefi='sudo grub-install --efi-directory=/boot/efi'
alias setkeymap='sudo localectl set-x11-keymap au'
alias setlocale='sudo localectl set-locale LANG=en_US.UTF-8'
alias setntp='sudo timedatectl set-ntp true'
alias sfcupd='sudo fc-cache -fv'
alias sfind='sudo find'
alias sged='sudo gedit'
alias shtop='sudo htop'
alias siptables='sudo iptables'
alias smandb='sudo mandb'
alias smkgrubconf='sudo grub-mkconfig -o /boot/grub/grub.cfg'
alias smount='sudo mount'
alias smvp='sudo mkdir -vp'
alias smv='sudo mv'
alias snn='sudo rnano -w'
alias sopenvpn='sudo openvpn'
alias spcleanup='sudo pacman -Rns $(pacman -Qtdq)'
alias spk='sudo pacman-key'
alias splistaur='sudo pacman -Qqem'
alias splistex='sudo pacman -Qqe'
alias splistor='sudo pacman -Qqet'
alias spqo='sudo pacman -Qo'
alias spqs='sudo pacman -Qs'
alias spr='sudo pacman -Rn'
alias spsi='sudo pacman -Sii'
alias spss='sudo pacman -Ss'
alias sps='sudo pacman -S'
alias sp='sudo pacman'
alias spunlock='sudo rm /var/lib/pacman/db.lck'
alias spupdate='sudo pacman -Syyu'
alias spupd='sudo pacman -Syyu'
alias srflct='sudo reflector'
alias srmirrors='srflct -a 6 -l 20 --sort score --save /etc/pacman.d/mirrorlist'
alias srmlogoutlock='sudo rm /tmp/arcologout.lock'
alias srmpyextmng='sudo rm /usr/lib/python3.11/EXTERNALLY-MANAGED'
alias srm='sudo rm'
alias srmr='sudo rm -r'
alias stee='sudo tee'
alias sucp='sudo cp -rp'
alias sufw='sudo ufw'
alias sumount='sudo umount'
alias suspend='sudo systemctl suspend'
alias svbm='sudo /usr/local/bin/arcolinux-vbox-share'
alias swg-quick='sudo wg-quick'
alias sysfailed='sudo systemctl list-units --failed'
alias sysfailrs='sudo systemctl reset-failed'
alias syslist='sudo systemctl list-unit-files --all'
alias sysreload='sudo systemctl daemon-reload'
alias ytaac="sudo yt-dlp --extract-audio --audio-format aac "
alias ytbest="sudo yt-dlp --extract-audio --audio-format best "
alias ytflac="sudo yt-dlp --extract-audio --audio-format flac "
alias ytmp3="sudo yt-dlp --extract-audio --audio-format mp3 "
alias ytbest="sudo yt-dlp -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]' "
################################################################################
# 5 SPEEDDIAL
################################################################################
alias sdaliases="$EDITOR $ANARCHY/aliases"
alias sdawesome="$EDITOR $CONFIG/awesome/rc.lua"
alias sdbashrc="$EDITOR $HOME/.bashrc"
alias sdcleanup="$EDITOR $ANARCHY/cleanup"
alias sdmimeapps="$EDITOR $CONFIG/mimeapps.list"
alias sdpractice="$EDITOR $HOME/.local/share/Steam/steamapps/common/\
Counter-Strike\ Global\ Offensive/game/csgo/cfg/practice.cfg"
alias sdrofilaunch="$EDITOR $CONFIG/awesome/rofi/launcher.rasi"
alias sdterminator="$EDITOR $CONFIG/terminator/config"
alias sdubashrc="sudo $EDITOR /root/.bashrc"
alias sdvariables="$EDITOR $ANARCHY/variables"
alias sudircolors="sudo $EDITOR /etc/DIR_COLORS"
alias sugpg="sudo $EDITOR /etc/pacman.d/gnupg/gpg.conf"
alias suhosts="sudo $EDITOR /etc/hosts"
alias suhtop="sudo $EDITOR /etc/htopc"
alias sujackd="sudo $EDITOR /etc/jackd"
alias sulimits="sudo $EDITOR /etc/security/limits.conf"
alias sunano="sudo $EDITOR /etc/nanorc"
alias suneofetch="sudo $EDITOR /etc/neofetch/config.conf"
alias sunmconf="sudo $EDITOR /etc/NetworkManager/NetworkManager.conf"
alias sunsswitch="sudo $EDITOR /etc/nsswitch.conf"
alias suovpncli2="sudo $EDITOR /etc/openvpn/ovpncli2.ovpn"
alias suovpncli3="sudo $EDITOR /etc/openvpn/ovpncli3.ovpn"
alias suovpnclient="sudo $EDITOR /etc/openvpn/client/ovpncli.ovpn"
alias suovpncli="sudo $EDITOR /etc/openvpn/ovpncli.ovpn"
alias supacman="sudo $EDITOR /etc/pacman.conf"
alias supchains="sudo $EDITOR /etc/proxychains.conf"
alias sureadline="sudo $EDITOR /etc/inputrc"
alias susshd="sudo $EDITOR /etc/ssh/sshd_config"
alias sussh="sudo $EDITOR /etc/ssh/ssh_config"
alias sutorrc="sudo $EDITOR /etc/tor/torrc"
alias sutorsocks="sudo $EDITOR /etc/tor/torsocks.conf"
alias suwgcli2="sudo $EDITOR /etc/wireguard/wgcli2.conf"
alias suwgcli3="sudo $EDITOR /etc/wireguard/wgcli3.conf"
alias suwgclient="sudo $EDITOR /etc/wireguard/wgcli.conf"
alias suwgcli="sudo $EDITOR /etc/wireguard/wgcli.conf"
alias suxinit="sudo $EDITOR /etc/X11/xinit/xinitrc"
alias suxprofile="sudo $EDITOR /etc/xprofile"
################################################################################
