#!/bin/bash
#shellcheck disable=SC1091
#                                       __|  |     __|    \     \ |  |  |  _ \
#                                      (     |     _|    _ \   .  |  |  |  __/
#                                     \___| ____| ___| _/  _\ _|\_| \__/  _|
########################################################################################################################
# ▸ ~/.anarchy/cleanup
########################################################################################################################
# 1 SOURCE FILES
########################################################################################################################
[ -f "$HOME/.anarchy/aliases" ] && . "$HOME/.anarchy/aliases"
[ -f "$HOME/.anarchy/variables" ] && . "$HOME/.anarchy/variables"
########################################################################################################################
# 2 FILE REMOVALS
########################################################################################################################
[ -f '/etc/profile.d/debuginfod.csh' ] && srm '/etc/profile.d/debuginfod.csh'
[ -f '/etc/profile.d/gawk.csh' ] && srm '/etc/profile.d/gawk.csh'
[ -f '/etc/profile.d/gawk.sh' ] && srm '/etc/profile.d/gawk.sh'
[ -f '/etc/profile.d/jre.csh' ] && srm '/etc/profile.d/jre.csh'
[ -f '/etc/profile.d/libreoffice-fresh.csh' ] && srm '/etc/profile.d/libreoffice-fresh.csh'
[ -f '/etc/profile.d/perlbin.csh' ] && srm '/etc/profile.d/perlbin.csh'
[ -f '/etc/profile.d/perlbin.sh' ] && srm '/etc/profile.d/perlbin.sh'
[ -f '/etc/profile.d/vte.csh' ] && srm '/etc/profile.d/vte.csh'
[ -f '/etc/X11/xinit/xinitrc.d/50-systemd-user.sh' ] && srm '/etc/X11/xinit/xinitrc.d/50-systemd-user.sh'
[ -f '/etc/X11/xinit/xinitrc.d/80xapp-gtk3-module.sh' ] && srm '/etc/X11/xinit/xinitrc.d/80xapp-gtk3-module.sh'
[ -f '/etc/xdg/autostart/gnome-keyring-pkcs11.desktop' ] && srm '/etc/xdg/autostart/gnome-keyring-pkcs11.desktop'
[ -f '/etc/xdg/autostart/gnome-keyring-secrets.desktop' ] && srm '/etc/xdg/autostart/gnome-keyring-secrets.desktop'
[ -f '/etc/xdg/autostart/gnome-keyring-ssh.desktop' ] && srm '/etc/xdg/autostart/gnome-keyring-ssh.desktop'
[ -f "$HOME/.aspell.en.prepl" ] && rm "$HOME/.aspell.en.prepl"
[ -f "$HOME/.aspell.en.pws" ] && rm "$HOME/.aspell.en.pws"
[ -f "$HOME/.bash_logout" ] && rm "$HOME/.bash_logout"
[ -f "$HOME/.bash_profile" ] && rm "$HOME/.bash_profile"
[ -f "$HOME/.fehbg" ] && rm "$HOME/.fehbg"
[ -f "$HOME/.git-credentials" ] && rm "$HOME/.git-credentials"
[ -f "$HOME/.ICEauthority" ] && rm "$HOME/.ICEauthority"
[ -f "$HOME/.lesshst" ] && rm "$HOME/.lesshst"
[ -f "$HOME/.nanorc" ] && rm "$HOME/.nanorc"
[ -f "$HOME/.profile" ] && rm "$HOME/.profile"
[ -f "$HOME/.pulse-cookie" ] && rm "$HOME/.pulse-cookie"
[ -f "$HOME/.python_history" ] && rm "$HOME/.python_history"
[ -f "$HOME/.sqlite_history" ] && rm "$HOME/.sqlite_history"
[ -f "$HOME/.wget-hsts" ] && rm "$HOME/.wget-hsts"
[ -f "$HOME/.Xresources" ] && rm "$HOME/.Xresources"
[ -f "$HOME/.xsession-errors.old" ] && rm "$HOME/.xsession-errors.old"
[ -f "$HOME/.xsession-errors" ] && rm "$HOME/.xsession-errors"
[ -f "$HOME/.xsessionrc" ] && rm "$HOME/.xsessionrc"
[ -f "$HOME/.xsession" ] && rm "$HOME/.xsession"
[ -f "$HOME/.zshrc" ] && rm "$HOME/.zshrc"
[ -f "$HOME/.zynaddsubfx-bank-cache.xml" ] && rm "$HOME/.zynaddsubfx-bank-cache.xml"
[ -f '/usr/share/nano-syntax-highlighting/nanorc.nanorc' ] && srm '/usr/share/nano-syntax-highlighting/nanorc.nanorc'
########################################################################################################################
# 3 FILE MODIFICATIONS
########################################################################################################################
[[ -f '/etc/ch1px0rg-rel' && -f '/etc/lsb-release' ]] && smv '/etc/ch1px0rg-rel' '/etc/lsb-release'
[[ -f '/usr/local/bin/arcolinux-graphical-target' && -f "$HOME/.local/bin/agt_mod" ]] &&
	smv "$HOME/.local/bin/agt_mod" '/usr/local/bin/arcolinux-graphical-target'
[ -f "$CONFIG/auostart/variety.desktop" ] && smv "$CONFIG/auostart/variety.desktop" "/etc/xdg/autostart"
[ -f "$HOME/.asoundrc" ] && mv "$HOME/.asoundrc" "$ALSA_HOME/asoundrc"
[ -f "$HOME/.gtkrc-2.0" ] && mv "$HOME/.gtkrc-2.0" "$GTK2_RC_FILES/gtkrc"
[ -f "$HOME/.screenrc" ] && mv "$HOME/.screenrc" "$SCREENRC"
########################################################################################################################
# 4 DIRECORY REMOVALS
########################################################################################################################
[ -d "$CONFIG/auostart" ] && rmr "$CONFIG/autostart"
[ -d "$HOME/.log" ] && rmr "$HOME/.log"
[ -d "$HOME/Music" ] && rmr "$HOME/Music"
[ -d "$HOME/Pictures" ] && rmr "$HOME/Pictures"
[ -d "$HOME/Public" ] && rmr "$HOME/Public"
[ -d "$HOME/.shared-ringdb" ] && rmr "$HOME/.shared-ringdb"
[ -d "$HOME/Templates" ] && rmr "$HOME/Templates"
[ -d "$HOME/.tor" ] && rmr "$HOME/.tor"
[ -d "$HOME/Videos" ] && rmr "$HOME/Videos"
[ -d "$HOME/.vital" ] && rmr "$HOME/.vital"
[ -d "$MONERO_HOME/.bitmonero/lmdb" ] && rmr "$MONERO_HOME/.bitmonero/lmdb"
[ -d '/home/root' ] && srm '/home/root'
########################################################################################################################
# 5 DIRECORY MODIFICATIONS
########################################################################################################################
[ ! -d "$ALSA_HOME" ] && mvp "$ALSA_HOME" &>'/dev/null'
[ ! -d "$AUDIO" ] && mvp "$AUDIO" &>'/dev/null'
[ ! -d "$GTK2_RC_FILES" ] && mvp "$GTK2_RC_FILES" &>'/dev/null'
[ -d "$HOME/.bin" ] && mv "$HOME/.bin" "$LOCAL/bin"
[ -d "$HOME/.cargo" ] && mv "$HOME/.cargo" "$CARGO_HOME"
[ -d "$HOME/.ccache" ] && mv "$HOME/.ccache" "$CCACHE_DIR"
[ -d "$HOME/Monero" ] && mv "$HOME/Monero" "$CONFIG/monero-project"
[ -d "$HOME/.pki" ] && mv "$HOME/.pki" "$PKI_HOME"
[ -d "$HOME/.pulse" ] && mv "$HOME/.pulse" "$PULSE_HOME"
[ -d "$HOME/.wine" ] && mv "$HOME/.wine" "$WINEPREFIX"
[ ! -d "$DEADBEEF_HOME" ] && mvp "$DEADBEEF_HOME" &>'/dev/null'
[ ! -d "$GIMP_HOME" ] && mvp "$GIMP_HOME" &>'/dev/null'
[ ! -d "$LOCAL" ] && mvp "$LOCAL" &>'/dev/null'
[ ! -d "$MONERO_HOME" ] && mvp "$MONERO_HOME" &>'/dev/null'
[ ! -d "$NANO_HOME/backup" ] && mvp "$NANO_HOME/backup" &>'/dev/null'
[ ! -d "$NANO_HOME" ] && mvp "$NANO_HOME" &>'/dev/null'
[ ! -d "$REPO_HOME" ] && mvp "$REPO_HOME" &>'/dev/null'
[ ! -d "$SQL_HOME" ] && mvp "$SQL_HOME" &>'/dev/null'
[ ! -d "$SSH_HOME" ] && mvp "$SSH_HOME" &>'/dev/null'
[ ! -d "$VISUAL" ] && mvp "$VISUAL" &>'/dev/null'
[ ! -d "$XDG_STATE_HOME/bash" ] && mvp "$XDG_STATE_HOME/bash" &>'/dev/null'
[ ! -d "$XDG_STATE_HOME" ] && mvp "$XDG_STATE_HOME" &>'/dev/null'
########################################################################################################################
# 6 POSITION LAST
########################################################################################################################
[ ! -d "$AUDIO/ccvst" ] && mvp "$AUDIO/ccvst" &>'/dev/null'
[ ! -d "$AUDIO/files" ] && mvp "$AUDIO/files" &>'/dev/null'
[ ! -d "$ARDOUR" ] && mvp "$ARDOUR" &>'/dev/null'
[ ! -d "$ARDOUR/plugins" ] && mvp "$ARDOUR/plugins" &>'/dev/null'
[ ! -d "$ARDOUR/projects" ] && mvp "$ARDOUR/projects" &>'/dev/null'
[ ! -d "$ARDOUR/templates" ] && mvp "$ARDOUR/templates" &>'/dev/null'
[ ! -d "$BLENDER" ] && mvp "$BLENDER" &>'/dev/null'
[ ! -d "$BLENDER/plugins" ] && mvp "$BLENDER/plugins" &>'/dev/null'
[ ! -d "$BLENDER/projects" ] && mvp "$BLENDER/projects" &>'/dev/null'
[ ! -d "$BLENDER/templates" ] && mvp "$BLENDER/templates" &>'/dev/null'
[ ! -d "$FLAVOUR/cursors" ] && mvp "$FLAVOUR/cursors" &>'/dev/null'
[ ! -d "$FLAVOUR/fonts" ] && mvp "$FLAVOUR/fonts" &>'/dev/null'
[ ! -d "$FLAVOUR/icons" ] && mvp "$FLAVOUR/icons" &>'/dev/null'
[ ! -d "$FLAVOUR/themes" ] && mvp "$FLAVOUR/themes" &>'/dev/null'
[ ! -d "$FLAVOUR/walls" ] && mvp "$FLAVOUR/walls" &>'/dev/null'
[ ! -d "$GIMP" ] && mvp "$GIMP" &>'/dev/null'
[ ! -d "$GIMP/plugins" ] && mvp "$GIMP/plugins" &>'/dev/null'
[ ! -d "$GIMP/projects" ] && mvp "$GIMP/projects" &>'/dev/null'
[ ! -d "$GIMP/templates" ] && mvp "$GIMP/templates" &>'/dev/null'
[ ! -d "$KDENLIVE" ] && mvp "$KDENLIVE" &>'/dev/null'
[ ! -d "$KDENLIVE/plugins" ] && mvp "$KDENLIVE/plugins" &>'/dev/null'
[ ! -d "$KDENLIVE/projects" ] && mvp "$KDENLIVE/projects" &>'/dev/null'
[ ! -d "$KDENLIVE/templates" ] && mvp "$KDENLIVE/templates" &>'/dev/null'
[ ! -d "$REAPER" ] && mvp "$REAPER" &>'/dev/null'
[ ! -d "$REAPER/plugins" ] && mvp "$REAPER/plugins" &>'/dev/null'
[ ! -d "$REAPER/projects" ] && mvp "$REAPER/projects" &>'/dev/null'
[ ! -d "$REAPER/templates" ] && mvp "$REAPER/templates" &>'/dev/null'
[ ! -d "$VISUAL/ccvst" ] && mvp "$VISUAL/ccvst" &>'/dev/null'
[ ! -d "$VISUAL/files" ] && mvp "$VISUAL/files" &>'/dev/null'
[ -f "$HOME/.bash_history" ] && mv "$HOME/.bash_history" "$XDG_STATE_HOME/bash/history"
########################################################################################################################
