#!/bin/bash
#80x
#                 _ \     \    __|   \  |   _ \    \ |   __|
#                 |  |   _ \   _|   |\/ |  (   |     | \__ \
#                ___/  _/  _\ ___| _|  _| \___/  _|\_| ____/
#
################################################################################
# ~ $ANARCHY/daemons
################################################################################
# ~ man -P 'less +/DESCRIPTION' 'daemon(7)'
################################################################################
# ~ Variables & Daemon List (1)
################################################################################
LOGFL="$LOG/daemons.log"
LOCKFL='/tmp/daemons.lck'
DATE=$(date '+%d/%m/%y %H:%M:%S')
GKDARGS='--daemonize --components=pkcs11,secrets,ssh'
DAEMONS=(
	'acpid'
	'avahi-daemon'
	'bluetooth'
	'cups'
	'dbus'
	'fstrim'
	'graphical.target'
	'multi-user.target'
	'NetworkManager'
	'NetworkManager-wait-online'
	'ntpd'
	'sshd'
	'systemd-homed'
	'systemd-timesyncd'
	#'vboxservice'
)
################################################################################
# ~ Manage Start Process (2)
################################################################################
log_func(){
	echo "$DATE | $1" >>"$LOGFL"
}

check_deps(){
	for CMD in systemctl pgrep gnome-keyring-daemon sudo; do
		if ! command -v "$CMD" &>'/dev/null'; then
			echo "Error: $CMD is not installed." >&2
			exit 1
		fi
	done
}

# Manage gnome-keyring-daemon
gkd_func(){
	if ! pgrep -f gnome-keyring-daemon &>'/dev/null'; then
		if ! gnome-keyring-daemon --start "$GKDARGS"; then
			gnome-keyring-daemon --start "$GKDARGS" >>"$LOGFL" 2>&1 ||
			log_func 'Error starting gnome-keyring-daemon'
		fi
	else
		if ! gnome-keyring-daemon --replace "$GKDARGS"; then
			gnome-keyring-daemon --replace "$GKDARGS" >>"$LOGFL" 2>&1 ||
			log_func 'Error starting gnome-keyring-daemon'
		fi
	fi
}

enable_daemon(){
	if ! systemctl is-enabled --quiet "$1"; then
		sudo systemctl enable "$1" | tee -a "$LOGFL" 2>&1 ||
		log_func "Error enabling $1"
	fi
}

start_daemon(){
	if ! systemctl is-active --quiet "$1"; then
		sudo systemctl start "$1" | tee -a "$LOGFL" 2>&1 ||
		log_func "Error starting $1"
	fi
}

check_deps
if [ ! -f "$LOCKFL" ]; then clear
	for DAEMON in "${DAEMONS[@]}"; do
		enable_daemon "$DAEMON"
	done
	for DAEMON in "${DAEMONS[@]}"; do
		start_daemon "$DAEMON"
	done
	gkd_func &>'/dev/null'
	echo 'Probatissima' >"$LOCKFL"
	sleep 1; clear
fi

unset DAEMON DAEMONS DATE GKDARGS LOCKFL LOGFL
