#!/bin/bash
#            \ \   /  \    _ \ _ _|    \    _ )  |     __|   __|
#             \ \ /  _ \     /   |    _ \   _ \  |     _|  \__ \
#              \_/ _/  _\ _|_\ ___| _/  _\ ___/ ____| ___| ____/
################################################################################
# ▸ ~/.anarchy/variables
################################################################################
# 1 SHOPT OPTIONS
################################################################################
shopt -s histappend
shopt -s cmdhist
shopt -s lithist
shopt -s autocd
shopt -s cdspell
shopt -s dirspell
shopt -s cdable_vars
shopt -s dotglob
shopt -s extglob
shopt -s globstar
shopt -s nocaseglob
shopt -s progcomp
shopt -s hostcomplete
shopt -s expand_aliases
shopt -s progcomp_alias
shopt -s extquote
shopt -s huponexit
shopt -s gnu_errfmt
shopt -s sourcepath
shopt -s checkwinsize
shopt -s complete_fullquote
shopt -s interactive_comments
shopt -s no_empty_cmd_completion
################################################################################
# 4 PATH DIRECTIVES
################################################################################
export PATH="\
$HOME/.bin:\
$HOME/.local/bin:\
$HOME/.local/lib/python3.10/site-packages:\
$HOME/.local/lib/python3.11/site-packages:\
$HOME/.local/share/gem/ruby/3.0.0/gems:\
/bin:\
/opt/cuda/bin:\
/opt/cuda/nsight_compute:\
/opt/cuda/nsight_systems/bin:\
/opt/discord:\
/opt/vivaldi:\
/usr/bin:\
/usr/bin/core_perl:\
/usr/bin/site_perl:\
/usr/bin/vendor_perl:\
/usr/lib/jvm/default/bin:\
/usr/lib/polkit-gnome:\
/usr/lib/python3.10/site-packages:\
/usr/lib/python3.11/site-packages:\
/usr/local/bin:\
/usr/local/sbin:\
/usr/sbin:\
/usr/share/drbl/bin"
################################################################################
# 5 HOME LAYOUT
################################################################################
export LOCAL="$HOME/.local"
export LIB="$LOCAL/lib"
export DATA="$LOCAL/share"
export CONFIG="$HOME/.config"
export CACHE="$HOME/.cache"
export CARGO_HOME="$DATA/cargo"
export CCACHE_DIR="$CACHE/ccache"
export XDG_DATA_HOME="$DATA"
export XDG_CACHE_HOME="$CACHE"
export XDG_CONFIG_HOME="$CONFIG"
export XDG_STATE_HOME="$LOCAL/state"
export XDG_DESKTOP_DIR="$HOME/Desktop"
export DESKTOP="$XDG_DESKTOP_DIR"
export XDG_DOCUMENTS_DIR="$HOME/Documents"
export DOCUMENTS="$XDG_DOCUMENTS_DIR"
export XDG_DOWNLOAD_DIR="$HOME/Downloads"
export DOWNLOADS="$XDG_DOWNLOAD_DIR"
#export XDG_RUNTIME_DIR="/run/user/1000"
export ANARCHY="$HOME/.anarchy"
export ARDOUR="$HOME/.audio/ardour"
export AUDIO="$HOME/.audio"
export BLENDER="$HOME/.visual/blender"
export FLAVOUR="$HOME/.flavour"
export GIMP="$HOME/.visual/gimp"
export INKSCAPE="$HOME/.visual/inkscape"
export KDENLIVE="$HOME/.visual/kdenlive"
export REAPER="$HOME/.audio/reaper"
export RUNDIR="/run/media/$USER"
export SETUP="$HOME/.setup"
export VISUAL="$HOME/.visual"
export XCURSOR_PATH="$FLAVOUR/cursors"
################################################################################
# 6 PROGRAM DIRECTORIES
################################################################################
export ALIEN_HOME="$DATA/alien"
export ALSA_HOME="$CONFIG/alsa"
export ARDOUR_HOME="$CONFIG/ardour8"
export AWESOME_HOME="$CONFIG/awesome"
export CADENCE_HOME="$CONFIG/Cadence"
export CURL_HOME="$CONFIG/curl"
export DEADBEEF_HOME="$CONFIG/deadbeef"
export FABLA_HOME="$DATA/openAV-Fabla2"
export GEDIT_HOME="$DATA/gedit"
export GIMP_HOME="$CONFIG/GIMP/2.10"
export GNUPGHOME="$HOME/.gnupg"
export GTK2_RC_FILES="$CONFIG/gtk-2.0"
export HTOP_HOME="$CONFIG/htop"
export JACK_HOME="$CONFIG/jack"
export KDENLIVE_HOME="$DATA/kdenlive"
export MONERO_HOME="$CONFIG/monero-project"
export NANO_HOME="$CONFIG/nano"
export OPENAI_HOME="$PYTHON_HOME/openai"
export PICOM_HOME="$CONFIG/picom"
export PKI_HOME="$DATA/pki"
export PULSE_HOME="$CONFIG/pulse"
export PYTHON_HOME="$LIB/python3.11/site-packages"
export REAPER_HOME="$CONFIG/REAPER"
export REPO_HOME="$HOME/.repos"
export ROFI_HOME="$CONFIG/rofi"
export RUBY_HOME="$DATA/gem/ruby/3.0.0"
export SQL_HOME="$HOME/.sql"
export SSH_HOME="$HOME/.ssh"
export STEAM_HOME="$HOME/.steam"
export TERMINATOR_HOME="$CONFIG/terminator"
export VIVALDI_HOME="$CONFIG/vivaldi"
export W3M_HOME="$DATA/w3m"
export WINEPREFIX="$DATA/wine"
export YAY_HOME="$DATA/yay"
################################################################################
# 7 INPUT VARS
################################################################################
export BROWSER='/bin/vivaldi-stable'
export DATE_LONG=$(date +'%H%M-%d%m-%Y')
export DATE_SHORT=$(date +'%d/%m/%y')
export EDITOR="/bin/nano --backupdir=$NANO_HOME/backup"
export FILEMANAGER='/bin/nemo'
export GIT_CONFIG_GLOBAL="$HOME/.gitconfig"
export GIT_CONFIG_SYSTEM='/etc/gitconfig'
export GIT_SSH_COMMAND='/bin/ssh'
#export GNOME_KEYRING_CONTROL='/run/user/1000/keyring/control'
export GRAPHICAL='/bin/gedit'
#export GTK_IM_MODULE='/bin/fcitx'
export GTK_IM_MODULE='/bin/ibus'
export INPUTRC='/etc/inputrc'
export MAILCLIENT='/bin/thunderbird'
#export QT_IM_MODULE='/bin/fcitx'
export QT_IM_MODULE='/bin/ibus'
export QT_QPA_PLATFORMTHEME='/bin/qt5ct'
#export QT_STYLE_OVERRIDE='/bin/kvantum'
export SCREENRC="$CONFIG/screenrc"
#export SSH_AUTH_SOCK='/run/user/1000/keyring/ssh'
export SUDO_ASKPASS='/usr/lib/ssh/x11-ssh-askpass'
export TERMINAL='/bin/terminator'
#export XINITRC='/etc/X11/xinit/xinitrc'
export XMODIFIERS='@im=dbus'
#export XMODIFIERS='@im=fcitx'
#export XSERVERRC='/etc/X11/xinit/xserverrc'
################################################################################
# 8 SHELL VARS
################################################################################
export TCOLS=$(tput cols)
export LESSCHARSET=utf-8
export USECOLOR=true
export COLORTERM=truecolor
export TERM=xterm-256color
export HISTSIZE=1000
export HISTFILESIZE=10000
export HISTCONTROL='ignoredups:erasedups'
export HISTFILE="$XDG_STATE_HOME/bash/history"
export MANPAGER="sh -c \"sed 's/'\''//g' | bat -l rb --theme ansi \
--wrap never --terminal-width $(($TCOLS-2))\""
################################################################################
