#!/bin/bash
#shellcheck disable=SC1090
#
#                  \ \  / _ _|   \ | _ _| __ __| _ \   __|
#                   >  <    |   .  |   |     |     /  (
#                   _/\_\ ___| _|\_| ___|   _|  _|_\ \___|
#
################################################################################
# ~ /etc/X11/xinit/xinitrc
# ~ $HOME/.xinitrc || $XDG_CONFIG_HOME/X11/xinitrc
################################################################################
# ▸ man 'xinit(1)' | less +/FILES
################################################################################
# 1 ~ SETUP ENVIRONMENT
################################################################################
export XAUTHORITY="$HOME/.Xauthority"
declare -a SOURCES
SOURCES[1]='/etc/X11/xinit/xinitrc.d/80-xapp-gtk3-module.sh'
SOURCES[2]='/etc/X11/xinit/xinitrc.d/40-libcanberra-gtk-module.sh'
SOURCES[3]='/etc/X11/xinit/xinitrc.d/61-cadence-session-inject.sh'
[ ! -f "$XAUTHORITY" ] && touch "$XAUTHORITY" &&
xauth generate "$DISPLAY" . trusted
################################################################################
# 2 ~ INITIALIZE CLIENT
################################################################################
for FL in "${SOURCES[@]}"; do
	test -f "$FL" && . "$FL" >'/dev/null' 2>&1
done
if [ "$(command -v systemctl --user import-environment)" ]; then
	systemctl --user import-environment DISPLAY XAUTHORITY
fi
if [ "$(which dbus-update-activation-environment)" ]; then
	dbus-update-activation-environment --systemd DISPLAY XAUTHORITY
fi
if [ ! $(pgrep -f gnome-keyring-daemon) ]; then
	eval "$(gnome-keyring-daemon --start --components=pkcs11,secrets,ssh,gpg)"
else
	eval "$(gnome-keyring-daemon --replace --components=pkcs11,secrets,ssh,gpg)"
fi
unset SOURCES
numlockx on &
xset s off &
xset -dpms &
#xset s noblank &
polkit-gnome-authentication-agent-1 &
sh -c "$HOME/.local/bin/setxwall" &
sleep 1
exec '/usr/bin/awesome'
